# AWS CodeBuild Build Specification for Building and packaging Orchestrator
version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package
            --template-file sam-template.yml
            --s3-bucket $TOTEM_BUCKET
            --output-template-file packaged-template.yml
            --s3-prefix=cloudformation/sam
artifacts:
  type: zip
  files:
    - packaged-template.yml
