---
swagger: 2.0
basePath: /Prod
info:
  title: totem-v3-orchestrator API
  version: 1.0.0
schemes:
  - https
paths:
  /hooks/github:
    post:
      summary: Handles github webhook
      description: Handles github webhook
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        202:
          description: 202 Accepted Response
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 202
        uri: ${stageVariables.WebhooksLambdaUri}
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

definitions:
  Empty:
    type: object
    title: Empty Schema
