AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GlobalStack:
    Description: Name of totem global stack
    Type: String
    MinLength: 1
    Default: 'totem-global'

  OrchestratorEnvironmentStack:
    Description: Name of orchestrator environment stack
    Type: String
    MinLength: 1
    Default: 'totem-orchestrator-environment'

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: swagger.yml
      Variables:
        WebhooksLambda: !Ref WebHooksLambda
        AwsRegion: !Ref AWS::Region
        AwsAccountId: !Ref AWS::AccountId

  WebHooksLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Environment:
        Variables: {}
      Role:
        Fn::ImportValue: !Sub "${OrchestratorEnvironmentStack}-OrchestratorLambdaRoleArn"
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/hooks/github'
            Method: post
