AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GlobalStack:
    Description: Name of totem global stack
    Type: String
    MinLength: 1
    Default: 'totem-global'

  OrchestratorEnvironmentStack:
    Description: Name of orchestrator environment stack
    Type: String
    MinLength: 1
    Default: 'totem-orchestrator-environment'

  Environment:
    Description: Orchestrator environment (development, production, etc)
    Type: String
    MinLength: 1
    Default: 'development'

  GitBranch:
    Type: String
    Description: Git branch for source repository
    MinLength: 1
    Default: feature_git-workflow


Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: 2.0
        basePath: /
        info:
          title: !Sub totem-v3-orchestrator-${Environment}
          description: !Sub Totem V3 Orchestrator API ${Environment} (${GitBranch})
          version: 1.0.0
        schemes:
          - https
        paths:

          /:
            get:
              summary: API Root
              description: API Root
              # operationId: getRoot
              produces:
                - application/json
              responses:
                "202":
                  description: 202 Accepted Response
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 202
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OrchestratorLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: GET
                type: aws_proxy


          /hooks/github:
            post:
              summary: Handles github webhook
              description: Handles github webhook
              # operationId: handleGithubWebhook
              consumes:
                - application/json
              produces:
                - application/json
              responses:
                "202":
                  description: 202 Accepted Response
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 202
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OrchestratorLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy

          /setup:
            put:
              summary: Create or update repository webhooks for totem-v3
              description: Create or update repository webhooks for totem-v3
              # operationId: setupWebhook
              consumes:
                - application/json
              produces:
                - application/json
              responses:
                "202":
                  description: 202 Accepted Response
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 202
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OrchestratorLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: PUT
                type: aws_proxy

        definitions:
          Empty:
            type: object
            title: Empty Schema

  OrchestratorLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Environment:
        Variables: {}
      Role:
        Fn::ImportValue: !Sub "${OrchestratorEnvironmentStack}-OrchestratorLambdaRoleArn"
      Events:
        RootApi:
          Type: Api
          Properties:
            Path: '/'
            Method: get
        WebhookApi:
          Type: Api
          Properties:
            Path: '/hooks/github'
            Method: post
        SetupApi:
          Type: Api
          Properties:
            Path: '/setup'
            Method: put

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGateway
        - '.execute-api.'
        - !Ref 'AWS::Region'

  SwaggerUrl:
    Description: URL of your API endpoint apigateway.us-west-2.amazonaws.com/restapis/ago90g4iff/stages/prod/exports/swagger
    Value: !Join
      - ''
      - - https://apigateway.
        - !Ref 'AWS::Region'
        - .amazonaws.com/restapis/
        - !Ref ApiGateway
        - /stages/prod/export/swagger