# Maps environment variables to orchestrator config (See https://github.com/lorenwest/node-config/wiki/Environment-Variables)
github:
  token: GITHUB_TOKEN
  hookDef:
    config:
      secret: WEBHOOK_SECRET
aws:
  region: AWS_REGION